name: first

on: push

jobs:
  
  # job identifier
  # jobs run in parallel by default
  job1:
    name: First job
    runs-on: ubunut-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: env | sort

  job2:
    name: Second job
    runs-on: windows-latest
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: "Get-ChildItem Env:| Sort-Object Name"

  job3:
    name: Third job
    runs-on: macos-latest
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: env | sort

    
